# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'training2-4-2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for training2-4-2
	pod 'AFNetworking', '~> 3.0';
  target 'training2-4-2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'training2-4-2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
