# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'traning2-3-2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for traning2-3-2
  pod ‘FMDB’

  target 'traning2-3-2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'traning2-3-2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
